{% set name = "midas2" %}
{% set version = "2.0.0.rc3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/4e/f6/75f3c24448b4180cb1b4166bfdbec907bfb94803aaa74b9a912a7d5df52c/midas2-2.0.0rc2.tar.gz
  sha256: 5096efe2de0c9531ff39d7e0bf62acf9c40b06ee90e9c19c49b28a07123bf3f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-dependencies

requirements:
  host:
    - python >=3.9,<3.10
    - pip
    - setuptools
  run:
    - python >=3.9,<3.10
    - tbb ==2021.11.0
    - numpy >=1.26.4
    - biopython >=1.83
    - gffutils >=0.12
    - bowtie2 >=2.5.3
    - samtools >=1.19.2
    - pysam >=0.22.0
    - hs-blastn ==0.0.5
    - blast >=2.14.0
    - awscli >=1.32.48
    - lz4 >=4.3.3
    - prokka >=1.14.6
    - vsearch >=2.27.0
    - seqkit >=2.7.0
    - cd-hit >=4.8.1
    - pandas >=2.2.0
    - gawk >=5.3.0
    - pybedtools >=0.9.1

test:
  imports:
    - midas2
  commands:
    - midas2 --version
    - midas2 run_snps --help

about:
  home: "https://github.com/czbiohub/MIDAS2"
  license: MIT License
  license_family: MIT
  summary: "Metagenomic Intra-Species Diversity Analysis 2"
